import { useRef } from 'react';
import QRCode from 'react-qr-code';
import { useStore } from '../store/useStore';
import type { Table, Guest } from '../types';
import { generateTableQRUrl } from '../utils/qrCodeUtils';
import './QRCodePrintView.css';

interface QRCodePrintViewProps {
  onClose: () => void;
}

export function QRCodePrintView({ onClose }: QRCodePrintViewProps) {
  const printRef = useRef<HTMLDivElement>(null);
  const { event } = useStore();

  if (!event) {
    return null;
  }

  const tables = event.tables;

  const handlePrint = () => {
    window.print();
  };

  const getGuestCount = (tableId: string) => {
    return event.guests.filter(
      (g: Guest) => g.tableId === tableId && g.rsvpStatus === 'confirmed'
    ).length;
  };

  return (
    <div className="qr-print-view">
      {/* Header - hidden when printing */}
      <div className="qr-print-header no-print">
        <div className="qr-print-header-content">
          <h2>Print All QR Codes</h2>
          <p className="qr-print-subtitle">
            {tables.length} table{tables.length !== 1 ? 's' : ''} •{' '}
            {event.name}
          </p>
        </div>
        <div className="qr-print-actions">
          <button className="btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn-primary" onClick={handlePrint}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            Print QR Codes
          </button>
        </div>
      </div>

      {/* Print content */}
      <div className="qr-print-content" ref={printRef}>
        {/* Print title - only visible when printing */}
        <div className="print-title print-only">
          <h1>{event.name}</h1>
          {event.date && <p className="event-date">{event.date}</p>}
          <p className="subtitle">Table QR Codes</p>
        </div>

        {/* QR Grid */}
        <div className="qr-grid">
          {tables.map((table: Table) => {
            const qrUrl = generateTableQRUrl(event, table);
            const guestCount = getGuestCount(table.id);

            return (
              <div key={table.id} className="qr-card">
                <div className="qr-code-wrapper">
                  <QRCode
                    value={qrUrl}
                    size={150}
                    level="M"
                    bgColor="#ffffff"
                    fgColor="#000000"
                  />
                </div>
                <div className="qr-card-info">
                  <h3 className="table-name">{table.name}</h3>
                  <p className="table-meta">
                    {guestCount} guest{guestCount !== 1 ? 's' : ''} •{' '}
                    {table.capacity} seats
                  </p>
                </div>
                <p className="scan-hint">Scan to view tablemates</p>
              </div>
            );
          })}
        </div>

        {/* Print footer */}
        <div className="print-footer print-only">
          <p>Generated by Seatify</p>
        </div>
      </div>
    </div>
  );
}
